### ISSUE TITLE
incomplete type is not allowed error with Intel 19.1 compiler

### ISSUE THREAD

**Issue by loopless** [taocpp/operators#17]
When trying an example with my template class I get the following errors. The class MathVec  had been pre-declared before this definition.

tao\operators.hpp(480): error : incomplete type is not allowed
1>        TAO_OPERATORS_BASIC_OP( addable, +);

template <class T>
class MathVec : public VecView, tao::operators::addable< MathVec<T> >
{
public:
....
}

**Comment by loopless** [comment]
This is an incompatibility with the Intel 19.1 compiler. If I switch to the Visual C++ Compiler ( 2019) the code compiles without error.
I can reproduce the issue with the  MyInt example code.

**Comment by d-frey** [comment]
I'm afraid there is not much we can do in this case. As you can see MSVC, GCC, and Clang all accept the code just fine. If a compiler doesn't follow the standard enough, there is probably no way to fix this, at least this is what I read into "incomplete type is not allowed". The library itself it pretty straight forward and the compiler needs to be able to handle the order in which things are declared/defined. If you know any way to fix it for the Intel compiler, feel free to send a PR.
