### ISSUE TITLE
Incomplete types

### ISSUE THREAD

**Issue by FrankHB** [taocpp/operators#5]
The noexcept-specification needs to instantiate the type parameter being used, thus the instance of `Template<S>` is generally ill-formed to be used in base-specifier-list of definition of `S`. Because before the closing `}` of the definition of `S`, `S` is an incomplete type, so the operand in noexcept-specification in member declarations of instantiated `Template<S>` definition is ill-formed. This problem does not occur in boost.operators.

(Clang++ and G++ may differ here. Though the diagnostics of Clang++ is awful, it should be right.)

**Comment by d-frey** [comment]
I tried to reproduce the problem, but the following seems to work with both GCC and Clang:

    struct S : tao::operators::addable< S >
    {
      S() {}
      S( const S& a, const S& b ) : S( a + b ) {}
      S& operator+=( const S& ) noexcept { return *this; }
    };

    S s;
    S s2( s, s );

Could you provide a testcase, the compiler and exact version you used and the output it produces? Thanks.

**Comment by FrankHB** [comment]
Sorry, I've got it wrong. The diagnostics were actually irrelevant. My fault.

In my case, the code is something like:

```
struct S : tao::operators::addable<S>
{
  S() {}
  S( const S& a, const S& b ) : S( a + b ) {}
  S& operator+=( const S& ) noexcept { return *this; }

	template <class T>
	static constexpr bool
	test() noexcept(noexcept(std::declval<T>() + std::declval<T>()))
	{
		return true;
	}

	template <class T>
	struct C
	{
		static constexpr bool
		test() noexcept(noexcept(std::declval<T>() + std::declval<T>()))
		{
			return true;
		}
	};

	static constexpr bool value = test<S>();
	static constexpr bool value2 = C<S>::test();
};
```
which has nothing to do with the base class itself.

Clang++ 3.7 did show something like [this](https://llvm.org/bugs/show_bug.cgi?id=12583). I can't reproduce it after cleanup of some other mess...
