### ISSUE TITLE
constexpr support

### ISSUE THREAD

**Issue by johelegp** [taocpp/operators#7]
Have you considered adding `constexpr` support to this great library? Unfortunately, it can't be done with the current approach (see https://github.com/foonathan/type_safe/issues/36).

Greetings,
Johel

**Comment by d-frey** [comment]
Yes, we considered it (in issue #6), but sadly it does not seem possible to support `constexpr`. As the library otherwise works well I prefer to keep it stable. In the future, things like the "spaceship-operator" (a currently proposed language extension) might be a far easier and suitable solution.
