### ISSUE TITLE
constexpr version of operator.h

### ISSUE THREAD

**Issue by gaspardpetit** [taocpp/operators#9]
I don't think there is a constexpr version of the methods provided in operators.h, would you be interested in one?  I'm wondering if this could be done by having on .h define something and include the operator.h header. The super clean, but the benefit would be that working in one file would implement the solution for both, what do you think?

**Comment by d-frey** [comment]
We considered it in issue #6, it seems there is no reasonable way to add `constexpr` support.

**Comment by keryell** [comment]
I just discovered this repository by hitting an issue about Boost.Operators not supporting `constexpr` operators...

After looking at the other issues https://github.com/taocpp/operators/issues/6 and https://github.com/taocpp/operators/issues/7, what about duplicating the operators in another namespace such as tao::operators_constexpr::ordered_field< X > or something similar, while waiting for better C++ to make further progress on `constexpr`?

**Comment by d-frey** [comment]
It would be a different library with a different API. It should also take into account future extensions of C++ like the spaceship-operator, etc. I think this points towards a completely separate library and not towards extending taocpp/operators.

**Comment by keryell** [comment]
I was thinking to something modest, actually. Such as the same but with `constexpr` when the programmer uses `tao::operators_constexpr::ordered_field< X >` instead of `tao::operators::ordered_field< X >`.
Does it makes sense?

**Comment by d-frey** [comment]
I just realized that the existing comparison operators might be easy candidates for `constexpr`, let me try to add it there first.

Would that be sufficient for you?

**Comment by d-frey** [comment]
Update: Looking good for GCC and Clang, not so much for Visual C++ which seems to have an issue. For now I've disabled MSVC. I'll document it in the next days, currently I'm a bit pressed on time.
